safe: true
source: .
destination: _site
lsi: false
markdown: rdiscount
pygments: true
permalink: pretty

project:
    name: Geovedic
    tagline: Geographic Distribution of Students of UDD
    github: "https://github.com/pnavarrc/geovedic"
